### ISSUE TITLE
Fonction getBooks()

### ISSUE THREAD

**Issue by aetech97** [ISEN-2020/book-service#16]
La fonction "getBooks()" dans le fichier "TestApi.js" ne retourne aucune valeur, car elle fait un simple console.log() pour afficher les livres de la table "Book_list". Pouvez-vous modifier cette fonction à fin qu'elle nous retourne une variable (de type tableau)?

**Comment by Nico-Heissler** [comment]
C'est modifié, la variable "result" renvoyé par la query SQL est un tableau avec pour chaque case une ligne de la table
