### ISSUE TITLE
create data base

### ISSUE THREAD

**Issue by skollnope** [ISEN-2020/book-service#3]
create a data base containing name, picking date, id, email...

**Comment by TheMightySheitan** [comment]
DB architecture schematics is coming soon

**Comment by TheMightySheitan** [comment]
[book_service_DB_infrastructure.pdf](https://github.com/ISEN-2020/book-service/files/5207143/book_service_DB_infrastructure.pdf)

**Comment by TheMightySheitan** [comment]
[book_service_DB_infrastructureV2.pdf](https://github.com/ISEN-2020/book-service/files/5207258/book_service_DB_infrastructureV2.pdf)

**Comment by TheMightySheitan** [comment]
DataBase OK
Alles gut!
